name: publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Semantic Versioning: major, minor, patch"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN_AUTOMATION }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          cache: yarn
          registry-url: "https://registry.npmjs.org"

      # configure git user used to push tag
      - name: Configure Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"


      - run: yarn install

      - name: publish major
        if: github.event.inputs.semver == 'major'
        run: yarn publish:major --no-verify-access

      - name: publish minor
        if: github.event.inputs.semver == 'minor'
        run: yarn publish:minor --no-verify-access

      - name: publish patch
        if: github.event.inputs.semver == 'patch'
        run: yarn publish:patch --no-verify-access
