name: publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Semantic Versioning: major, minor, patch"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN_AUTOMATION }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: yarn
          registry-url: "https://registry.npmjs.org"
          scope: "@kobakazu0429"
          always-auth : true

      # configure git user used to push tag
      - name: Configure Git User
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "ci@$GITHUB_ACTOR"

      - run: yarn install

      - name: publish major
        if: github.event.inputs.semver == 'major'
        run: yarn publish:major
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN_AUTOMATION }}

      - name: publish minor
        if: github.event.inputs.semver == 'minor'
        run: yarn publish:minor
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN_AUTOMATION }}

      - name: publish patch
        if: github.event.inputs.semver == 'patch'
        run: yarn publish:patch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN_AUTOMATION }}
