name: publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Semantic Versioning: major, minor, patch"
        required: true
        default: "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN_AUTOMATION }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16.9.1"
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install

      - name: publish major
        if: github.event.inputs.semver == 'major'
        run: yarn publish:major

      - name: publish minor
        if: github.event.inputs.semver == 'minor'
        run: yarn publish:minor

      - name: publish patch
        if: github.event.inputs.semver == 'patch'
        run: yarn publish:patch
