name: publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Semantic Versioning: major, minor, patch"
        required: true
        default: "patch"

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN_AUTOMATION }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
      - name: Setup .npmrc file for publish
        uses: actions/setup-node@v2
        with:
          node-version: "16.9.1"
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install

  publish_major:
    if: github.event.inputs.semver == 'major'
    runs-on: ubuntu-latest
    steps:
      - name: publish:major
      - run: yarn publish:major

  publish_minor:
    if: github.event.inputs.semver == 'minor'
    runs-on: ubuntu-latest
    steps:
      - name: publish:minor
      - run: yarn publish:minor

  publish_patch:
    if: github.event.inputs.semver == 'patch'
    runs-on: ubuntu-latest
    steps:
      - name: publish:patch
      - run: yarn publish:patch
